AllCops:
  Exclude:
    - config/unicorn.rb
    #- db/**
    - db/schema.rb
    - vendor/**/*
    - bin/**
  RunRailsCops: true

MethodLength:
  Max: 30

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false