language: node_js

before_install:
  - gem install sass
  - npm install

install:
  - gulp production

node_js:
  - '0.10'

deploy:
  provider: heroku
  app: jellyfish-ux-dev
  skip_cleanup: true
  api_key:
    secure: "VINB/PoU27DpJKUSvJf2bF1eAM6+EbOL7/MXSGrboyPZfSmcgCdT/VYoZEPSYVVZ9znCsB0myYZNaIvmt8GRJVIDe7hNxYnf5pjVhUD0e1cZsL9U90P6L1CSqKtzEvGgKBmRC8GbJmuC5yFd9cwj4d/98o9rd1zYiF8pGRfFmZY="

notifications:
  slack:
    secure: "aqxG0CKy5kHNyJ0N2qrQlS4i3OYT5Ty5sSgdTGujvxmmf2uL3aEeC0KPHEdELmgow+t3wCjdFdmAGxBLhzXJD0PzAKA5vEFgw9Tnyapz4MzUMjFwUq5+lP5R+HMziQcH2o32cI2D9oRGdtu2pZQr/A5UCnJnHfpRAMTHHDJv2qc="
    on_success: change
    on_failure: always