language: node_js
node_js:
- 0.1
notifications:
  slack:
    secure: lU71I+nRyzLBlFomd6XAHLEGwJhL6l4idw7jThVdyyFiWQbxI7KUryMgAWjU5YqZ0/POB0ou9a0cnsmnRC2Heuw3MibgBpbbwbfjhbgAc/vgQp04A/JGTYpky2OI7958SpFn3y89Uv8/CDKLnG1Hn8rHVwmj6RCOdf2WB8PUOB0=
deploy:
  provider: heroku
  app: jellyfish-ux-dev
  api_key:
    secure: It6RgD34mScWklzk8NxRBLanqDjxFX/hR+knUG3g81EXID+5LJHnjw/yz1J1MvHzWcIW1bgjkHVcAclI5tPVqh9o6oJ2tp2CTr9rmHgzSRt7upZlIiYR06tOBSWwTk6et62VdiDIlYUDN4wX/kK90SW5HDASn+ATon13s3kjgLA=
  run: 'echo "window.appConfig = {apiBasePath: \"http://jellyfish-core-dev.dpi.bah.com\"}" >> public/appConfig.js'
