language: ruby

rvm:
- 2.1.5

addons:
  postgresql: "9.3"
  code_climate:
      repo_token:
        secure: "ai6+gVEZwIp5NUkV4c6WEQ6xGpsQ8jtaXlMST9Yxoptx+PiU4U2IyBrPiuYQfBnCBHfHSSrFe0doGgQiWFDmUX2MlEvXRajoGupFhk+xNcMS1jdLN7K+ktfWenNmyQtCTVx+cLT05uhNrHI2NwxpObFMSR2iPVxtqswROGra5YA="

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

notifications:
  slack:
    secure: "QaNl/iAYVGEFz2zveWr6rSxH/VHUj/hqWGYJw0isjHQI4XPQIaNSe8wO3F5AXVADMa2/0Wf7ffGZJUpSciF06q/QAdzEV/fznIWX5p65piD/JoDjuCI/qvGmdzExZbWZVFmETF0mXrF77AsEk9ei/8Fv+UerHMSaJpn5LzHzzoE="
    on_success: change
    on_failure: always

script:
- bundle exec rspec
- bundle exec rubocop

deploy:
  provider: heroku
  api_key:
    secure: r0eHefnPazYspJ7c9Jrf1QqO5fAfSiUU8wc/2fcqfEmR5BH2/VDoin3Z9TfYCW2k7vZ5OUSKzEX25oelyV6rOoaEEX/nC7gZ3U0IS6cyPgpAd9ApcfXwyZo8XwIAnGtkG+B9x+xE4aeoro9FdqSALDF2U5n8dUlOvf3OXKSMgoE=
  app: jellyfish-core-dev
  run:
    - "rake db:schema:load"
    - "rake"
    - "rake db:seed"
    - "rake sample:jenkins"