language: ruby

rvm: 2.2.0

sudo: false

addons:
  postgresql: "9.4"
  code_climate:
      repo_token:
        secure: "ai6+gVEZwIp5NUkV4c6WEQ6xGpsQ8jtaXlMST9Yxoptx+PiU4U2IyBrPiuYQfBnCBHfHSSrFe0doGgQiWFDmUX2MlEvXRajoGupFhk+xNcMS1jdLN7K+ktfWenNmyQtCTVx+cLT05uhNrHI2NwxpObFMSR2iPVxtqswROGra5YA="

before_script:
  - bundle exec rake db:create

notifications:
  slack:
    secure: "htdM8Tv7Z2FLsRhwOhjpL7r2O5YJOVvt838SRcI2tLFWDGtdWD/lg5GlQ7swxOXaEYiPD8RjKMh27v9lb6fxKbi3Pdu8kwR7GmjAGwGB9h0JwnrESbiSGCCC+J6APvWdq5Vs7iGMFUS7oOjw8fzyyHeRRbyf0SWiT7S9EUt3dec="

script:
- bundle exec rspec
- bundle exec rubocop

deploy:
  provider: heroku
  api_key:
    secure: "ZDWFn6pTVtqg4DwXu0ge5wkFu8pVJV3c0px0KAXubOr8H0VNa4j1pOocS7JiCOAfsU1GVm1idyvCPS5Dyz5HqnZIqGYKS0TSiK4ezA10a1nb3MTPEiCtAyb6c/wxwPrtQ+7EvbI5oL7bWtXXhWXo7czNMG22+IhsQw3FPEnOxVQ="
  app: jellyfish-core-dev
  run: "rake db:schema:load spec db:seed sample:demo"
