language: ruby
cache:
  directories:
  - vendor/bundle
  - node_modules
  - bower_components
rvm: 2.3.0
node_js:
  - "0.12"
sudo: false
addons:
  postgresql: '9.4'
  code_climate:
    repo_token:
      secure: "LeGo12Mjgn3xs4FHklkCvszo3Prylu0oFPwb0kUxhbkxaHs6Me7q+JePQ9kM/ngUR/FcSOtIIC3OT+6X45RjzY0sJC8MNhhWQG6bQz529oR1lFT0n8F2dahvRBbbV87BIPxSfxHq4bj/2KeDJxo1yRaJ2gA5W4OSYo4wgoveQ6c="
before_install:
- echo "4.0.1-$TRAVIS_BUILD_NUMBER" > VERSION
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create
- npm install -g npm@2
- npm install -g gulp bower
- npm install
- bower install
- bundle install
script:
- gulp build
- gulp vet
- bundle exec rubocop
- bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "Y64rLj1ynOh4oEZZbsACPQJRcgQI3cNCyeNGfg6cxXrcSY9uBV60YcsqKOjC19q1kQAxOmI1iAZGDmj/1an/QN2Jp1owN3X+H50uJu2SLH72l37jiZ15ICDS86B4E4Ta7Um8S4lfzFamn2R3TQbyjowcjV7vnMb0EET7NQLY3bY="
  app: jellyfish-dev
  run: rake db:schema:load; rake spec; rake db:seed; rake sample:demo
  skip_cleanup: true
env:
  global:
    secure: oglFznpoXgadlL7TyQ7/XYHLUCKxKle7HY5+XEgox76++kWcWt9TyiYfscChHbV5ERartdrJgC+hrCz5QNyDTICMxi1eJrcyCJO9CRqVpeATW2RA+Rvedmg4XUBGqXowNSWuQVT5zZktS89dTgtoHo5sZUw2eqnEbGJ1XtIPDGs=
