language: node_js
node_js:
  - "0.10"
notifications:
  slack:
    secure: lU71I+nRyzLBlFomd6XAHLEGwJhL6l4idw7jThVdyyFiWQbxI7KUryMgAWjU5YqZ0/POB0ou9a0cnsmnRC2Heuw3MibgBpbbwbfjhbgAc/vgQp04A/JGTYpky2OI7958SpFn3y89Uv8/CDKLnG1Hn8rHVwmj6RCOdf2WB8PUOB0=
deploy:
  provider: heroku
  api_key:
    secure: r0eHefnPazYspJ7c9Jrf1QqO5fAfSiUU8wc/2fcqfEmR5BH2/VDoin3Z9TfYCW2k7vZ5OUSKzEX25oelyV6rOoaEEX/nC7gZ3U0IS6cyPgpAd9ApcfXwyZo8XwIAnGtkG+B9x+xE4aeoro9FdqSALDF2U5n8dUlOvf3OXKSMgoE=
  app: jellyfish-ux-dev
  run: 'echo "window.appConfig = {apiBasePath: \"http://jellyfish-core-dev.dpi.bah.com\"}" >> public/appConfig.js'
